#!/bin/bash

DOMAIN="$1"
MAIL="$2"

certbot-auto certonly --webroot --text \
--webroot-path "/var/lib/haproxy" \
--renew-by-default --agree-tos \
--email "$MAIL" -d "$DOMAIN"

cat /etc/letsencrypt/live/$DOMAIN/privkey.pem /etc/letsencrypt/live/$DOMAIN/fullchain.pem > /certs/$DOMAN.pem
