#!/bin/bash

DOMAIN="$1"
MAIL="$2"

certbot certonly --webroot --text \
--webroot-path "/var/lib/haproxy" \
--renew-by-default --agree-tos \
--email "$MAIL" -d "$DOMAIN"

/commands/certbot-concat-crt
